//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duser
    {
        public string id { get; set; }
        public string nickname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string quote { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
