//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public string categoryId { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string createOn { get; set; }
        public string userId { get; set; }
        public string tag { get; set; }
        public string image { get; set; }
        public Nullable<int> postView { get; set; }
        public Nullable<int> postLike { get; set; }
        public Nullable<int> isActive { get; set; }
        public string RawContent { get; set; }
    }
}
